In [1]:
import torch as tt
from torch.autograd import Variable as variable


x = tt.autograd.Variable(tt.randn((3)), requires_grad=True)
w = variable(tt.Tensor([2]), requires_grad=True)
b = variable(tt.Tensor([3]), requires_grad=True)

x = variable(tt.randn(3), requires_grad = True)
print(x)
y = 2 * x
print(y)
y.backward(tt.Tensor([1, 0.1, 0.01]))
print(x.grad)


tensor([ 0.3194, -0.5695,  1.1641], requires_grad=True)
tensor([ 0.6389, -1.1389,  2.3283], grad_fn=<MulBackward0>)
tensor([2.0000, 0.2000, 0.0200])
