In [2]:
from torch import Tensor

In [3]:
a = Tensor([[1,2,3],[3,4,5]])
a 

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [4]:
label = Tensor([1,2,3,1,3])

In [6]:
for i in label:
    print(i.item())

1.0
2.0
3.0
1.0
3.0


In [9]:
label[0]=3
label

tensor([3., 3., 3., 1., 3.])

In [15]:
from torch import zeros, ones

In [42]:
b = zeros(5)
print(b)
c = ones(5)
print(c)

tensor([0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1.])


In [19]:
from torch import cat

In [46]:
cat((b,c),0)

tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [6]:
import torch

In [33]:
x = torch.randn(2, 3)
x.size

<function Tensor.size>

In [26]:
torch.cat((x,x),1)

tensor([[ 0.2328, -0.7013,  0.6436,  0.2328, -0.7013,  0.6436],
        [ 0.8562,  2.0729, -0.4252,  0.8562,  2.0729, -0.4252]])

In [55]:
q = zeros(1,5)
q

tensor([[0., 0., 0., 0., 0.]])

In [1]:
print(q)
q[0][1]=1
print(q)

NameError: name 'q' is not defined

In [22]:
from torch import nn, Tensor, LongTensor
from torch.autograd import Variable

In [5]:
criterion = nn.CrossEntropyLoss()

In [23]:
a = Variable(Tensor([[1,0,0],[0,1,0],[0,0,1]]))
b = Variable(LongTensor([1,2,0]))
loss = criterion(a,b)
print(loss)

tensor(1.5514)


In [20]:
print(a)
print(b)

tensor([[1., 2., 0.],
        [1., 2., 0.],
        [1., 2., 0.]])
tensor([1., 2., 0.])


In [2]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
# ToTensor变成 0~1   Normalize变成 -1~1
data_tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])

# train属性是区别并对应加载训练集和测试机
train_dataset = datasets.MNIST(root='./data', train=True, transform=data_tf)
test_dataset  = datasets.MNIST(root='./data', train=False, transform=data_tf)

In [20]:
import scipy.misc

In [14]:
image, a = train_dataset[0]
#train_dataset[0]
#image = image[0]

#image = scipy.misc.toimage(image, cmin=0.0, cmax=1.0)#.save('./image.jpg')
#image.show()
#image

In [15]:
import torch

In [29]:
i = 0
for image, label in train_dataset:
    i += 1
    image = image[0]
    if i==1:
        total_image = image
    else:
        total_image = torch.cat((total_image, image),1)
    if i==5:
        break;
image_show = scipy.misc.toimage(total_image, cmin=0.0, cmax=1.0)#.save('./image.jpg')
#image_show.show()
#type(total_image.numpy())
total_image

c:\users\zd\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: `toimage` is deprecated!
`toimage` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use Pillow's ``Image.fromarray`` directly instead.
  # This is added back by InteractiveShellApp.init_path()


tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [46]:
from PIL import Image

In [61]:
image = Image.fromarray(image.numpy())

TypeError: fromarray() got an unexpected keyword argument 'cmin'

In [56]:
image.show()